export const AGENDA_GET = 'AGENDA_GET';
export const AGENDA_REQUEST = 'AGENDA_REQUEST';
export const AGENDA_RESPONSE = 'AGENDA_RESPONSE';
export const AGENDA_ERROR = 'AGENDA_ERROR';

export const ADD_AGENDA_WORD_REQUEST = 'ADD_AGENDA_WORD_REQUEST';
export const ADD_AGENDA_WORD_RESPONSE = 'ADD_AGENDA_WORD_RESPONSE';
export const ADD_AGENDA_WORD_ERROR = 'ADD_AGENDA_WORD_ERROR';

export const ADD_WORD_BUTTON_STATUS = 'ADD_WORD_BUTTON_STATUS';