export const WORD_REQUEST = 'WORD_REQUEST';
export const WORD_RESPONSE = 'WORD_RESPONSE';
export const WORD_ERROR = 'WORD_ERROR';

export const ADD_WORD_REQUEST = 'ADD_WORD_REQUEST';
export const ADD_WORD_RESPONSE = 'ADD_WORD_RESPONSE';
export const ADD_WORD_ERROR = 'ADD_WORD_ERROR';

export const UPDATE_WORD_REQUEST = 'UPDATE_WORD_REQUEST';
export const UPDATE_WORD_RESPONSE = 'UPDATE_WORD_RESPONSE';
export const UPDATE_WORD_ERROR = 'UPDATE_WORD_ERROR';

export const DELETE_WORD_REQUEST = 'DELETE_WORD_REQUEST';
export const DELETE_WORD_ERROR = 'DELETE_WORD_ERROR';

export const UPDATE_WORD_ORDER_REQUEST = 'UPDATE_WORD_ORDER_REQUEST';
export const UPDATE_WORD_ORDER_RESPONSE = 'UPDATE_WORD_ORDER_RESPONSE';
export const UPDATE_WORD_ORDER_ERROR = 'UPDATE_WORD_ORDER_ERROR';

export const ADD_WORD_BUTTON_STATUS = 'ADD_WORD_BUTTON_STATUS';