export const WORD_SEARCH_GET = 'WORD_SEARCH_GET';
export const WORD_SEARCH_REQUEST = 'WORD_SEARCH_REQUEST';
export const WORD_SEARCH_RESPONSE = 'WORD_SEARCH_RESPONSE';
export const WORD_SEARCH_ERROR = 'WORD_SEARCH_ERROR';
