name: Build/release

on:
  pull_request:
    types: [ closed ]
    branches: main

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Tag Check
        run: |
          echo ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          use_vue_cli: "true"
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}